import json

def write_d1():
    elements = [
        {"type":"text","id":"title","x":290,"y":10,"width":420,"height":28,
         "text":"Bridge Protocol Evolution - v1 (Env-based) vs v2 (Env-less)",
         "originalText":"Bridge Protocol Evolution - v1 (Env-based) vs v2 (Env-less)",
         "fontSize":20,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10001,"version":1,"versionNonce":10002,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # V1 header
        {"type":"text","id":"v1_header","x":40,"y":60,"width":200,"height":25,
         "text":"v1  Env-based (Legacy)",
         "originalText":"v1  Env-based (Legacy)",
         "fontSize":16,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#FF6B6B","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10101,"version":1,"versionNonce":10102,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # V1 Step 1
        {"type":"rectangle","id":"v1_step1","x":40,"y":95,"width":260,"height":50,
         "strokeColor":"#FF6B6B","backgroundColor":"#2A1520","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10201,"version":1,"versionNonce":10202,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"v1_step1_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"v1_step1_text","x":50,"y":100,"width":240,"height":40,
         "text":"Register Environment\nGET env_id + env_secret",
         "originalText":"Register Environment\nGET env_id + env_secret",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10203,"version":1,"versionNonce":10204,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"v1_step1","lineHeight":1.25},

        {"type":"arrow","id":"v1_arrow1","x":170,"y":145,"width":0,"height":15,
         "strokeColor":"#FF6B6B","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10301,"version":1,"versionNonce":10302,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"points":[[0,0],[0,15]],
         "startBinding":{"elementId":"v1_step1","focus":0.5,"gap":0},
         "endBinding":{"elementId":"v1_step2","focus":0.5,"gap":0},
         "startArrowhead":None,"endArrowhead":"arrow"},

        {"type":"rectangle","id":"v1_step2","x":40,"y":160,"width":260,"height":50,
         "strokeColor":"#FFB84D","backgroundColor":"#1E2D4A","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10401,"version":1,"versionNonce":10402,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"v1_step2_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"v1_step2_text","x":50,"y":165,"width":240,"height":40,
         "text":"Long-poll /work\nGET work_secret (session_id + worker_jwt)",
         "originalText":"Long-poll /work\nGET work_secret (session_id + worker_jwt)",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10403,"version":1,"versionNonce":10404,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"v1_step2","lineHeight":1.25},

        {"type":"arrow","id":"v1_arrow2","x":170,"y":210,"width":0,"height":15,
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10501,"version":1,"versionNonce":10502,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"points":[[0,0],[0,15]],
         "startBinding":{"elementId":"v1_step2","focus":0.5,"gap":0},
         "endBinding":{"elementId":"v1_step3","focus":0.5,"gap":0},
         "startArrowhead":None,"endArrowhead":"arrow"},

        {"type":"rectangle","id":"v1_step3","x":40,"y":225,"width":260,"height":50,
         "strokeColor":"#6C63FF","backgroundColor":"#1A1A2E","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10601,"version":1,"versionNonce":10602,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"v1_step3_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"v1_step3_text","x":50,"y":230,"width":240,"height":40,
         "text":"Decode work_secret\nEstablish WebSocket / HybridTransport",
         "originalText":"Decode work_secret\nEstablish WebSocket / HybridTransport",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10603,"version":1,"versionNonce":10604,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"v1_step3","lineHeight":1.25},

        {"type":"arrow","id":"v1_arrow3","x":170,"y":275,"width":0,"height":15,
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10701,"version":1,"versionNonce":10702,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"points":[[0,0],[0,15]],
         "startBinding":{"elementId":"v1_step3","focus":0.5,"gap":0},
         "endBinding":{"elementId":"v1_step4","focus":0.5,"gap":0},
         "startArrowhead":None,"endArrowhead":"arrow"},

        {"type":"rectangle","id":"v1_step4","x":40,"y":290,"width":260,"height":50,
         "strokeColor":"#00D4AA","backgroundColor":"#16213E","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10801,"version":1,"versionNonce":10802,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"v1_step4_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"v1_step4_text","x":50,"y":295,"width":240,"height":40,
         "text":"Execute session\nPOST /stop",
         "originalText":"Execute session\nPOST /stop",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10803,"version":1,"versionNonce":10804,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"v1_step4","lineHeight":1.25},

        # Loop arrow back
        {"type":"arrow","id":"v1_loop_arrow","x":300,"y":315,"width":0,"height":0,
         "strokeColor":"#718096","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10901,"version":1,"versionNonce":10902,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,
         "points":[[0,0],[80,0],[80,-155],[-20,-155]],
         "startBinding":{"elementId":"v1_step4","focus":1.0,"gap":0},
         "endBinding":{"elementId":"v1_step2","focus":1.0,"gap":0},
         "startArrowhead":None,"endArrowhead":"arrow"},
        {"type":"text","id":"v1_loop_label","x":360,"y":215,"width":80,"height":16,
         "text":"Continue polling",
         "originalText":"Continue polling",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#718096","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":10903,"version":1,"versionNonce":10904,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        {"type":"text","id":"v1_label","x":40,"y":350,"width":280,"height":16,
         "text":"4 APIs, 3 roundtrips, env lifecycle management",
         "originalText":"4 APIs, 3 roundtrips, env lifecycle management",
         "fontSize":11,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#A0AEC0","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":11001,"version":1,"versionNonce":11002,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # V2 header
        {"type":"text","id":"v2_header","x":500,"y":60,"width":220,"height":25,
         "text":"v2  Env-less (New)",
         "originalText":"v2  Env-less (New)",
         "fontSize":16,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20101,"version":1,"versionNonce":20102,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        {"type":"rectangle","id":"v2_step1","x":480,"y":95,"width":260,"height":50,
         "strokeColor":"#00D4AA","backgroundColor":"#16213E","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20201,"version":1,"versionNonce":20202,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"v2_step1_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"v2_step1_text","x":490,"y":100,"width":240,"height":40,
         "text":"POST /sessions\nsession_id (OAuth, no env_id)",
         "originalText":"POST /sessions\nsession_id (OAuth, no env_id)",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20203,"version":1,"versionNonce":20204,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"v2_step1","lineHeight":1.25},

        {"type":"arrow","id":"v2_arrow1","x":610,"y":145,"width":0,"height":15,
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20301,"version":1,"versionNonce":20302,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"points":[[0,0],[0,15]],
         "startBinding":{"elementId":"v2_step1","focus":0.5,"gap":0},
         "endBinding":{"elementId":"v2_step2","focus":0.5,"gap":0},
         "startArrowhead":None,"endArrowhead":"arrow"},

        {"type":"rectangle","id":"v2_step2","x":480,"y":160,"width":260,"height":50,
         "strokeColor":"#6C63FF","backgroundColor":"#1A1A2E","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20401,"version":1,"versionNonce":20402,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"v2_step2_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"v2_step2_text","x":490,"y":165,"width":240,"height":40,
         "text":"POST /bridge\nworker_jwt + expires_in + api_base_url",
         "originalText":"POST /bridge\nworker_jwt + expires_in + api_base_url",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20403,"version":1,"versionNonce":20404,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"v2_step2","lineHeight":1.25},

        {"type":"arrow","id":"v2_arrow2","x":610,"y":210,"width":0,"height":15,
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20501,"version":1,"versionNonce":20502,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"points":[[0,0],[0,15]],
         "startBinding":{"elementId":"v2_step2","focus":0.5,"gap":0},
         "endBinding":{"elementId":"v2_step3","focus":0.5,"gap":0},
         "startArrowhead":None,"endArrowhead":"arrow"},

        {"type":"rectangle","id":"v2_step3","x":480,"y":225,"width":260,"height":50,
         "strokeColor":"#00D4AA","backgroundColor":"#152A20","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20601,"version":1,"versionNonce":20602,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"v2_step3_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"v2_step3_text","x":490,"y":230,"width":240,"height":40,
         "text":"SSE connection\nBidirectional streaming established",
         "originalText":"SSE connection\nBidirectional streaming established",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20603,"version":1,"versionNonce":20604,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"v2_step3","lineHeight":1.25},

        {"type":"arrow","id":"v2_arrow3","x":610,"y":275,"width":0,"height":15,
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20701,"version":1,"versionNonce":20702,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"points":[[0,0],[0,15]],
         "startBinding":{"elementId":"v2_step3","focus":0.5,"gap":0},
         "endBinding":{"elementId":"v2_step4","focus":0.5,"gap":0},
         "startArrowhead":None,"endArrowhead":"arrow"},

        {"type":"rectangle","id":"v2_step4","x":480,"y":290,"width":260,"height":50,
         "strokeColor":"#FFB84D","backgroundColor":"#1E2D4A","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20801,"version":1,"versionNonce":20802,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"v2_step4_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"v2_step4_text","x":490,"y":295,"width":240,"height":40,
         "text":"JWT refresh before expiry\nHeartbeat keeps-alive",
         "originalText":"JWT refresh before expiry\nHeartbeat keeps-alive",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":20803,"version":1,"versionNonce":20804,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"v2_step4","lineHeight":1.25},

        {"type":"text","id":"v2_label","x":480,"y":350,"width":260,"height":16,
         "text":"2 APIs, 1 roundtrip, stateless sessions",
         "originalText":"2 APIs, 1 roundtrip, stateless sessions",
         "fontSize":11,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#A0AEC0","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":21001,"version":1,"versionNonce":21002,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Comparison
        {"type":"text","id":"comp_header","x":40,"y":385,"width":200,"height":20,
         "text":"Comparison",
         "originalText":"Comparison",
         "fontSize":14,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":30001,"version":1,"versionNonce":30002,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        {"type":"rectangle","id":"comp_box","x":40,"y":410,"width":700,"height":175,
         "strokeColor":"#2D3748","backgroundColor":"#0D1117","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":30101,"version":1,"versionNonce":30102,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"comp_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"comp_text","x":60,"y":415,"width":660,"height":165,
         "text":"Aspect          v1                     v2\nEnv required    Yes                    No\nTransport       WebSocket + Hybrid     SSE + CCRClient\nAuth            env_secret -> worker   OAuth JWT\n                jwt                    \nComplexity      4 API calls            2 API calls\nRoundtrips      3 before streaming     1 before streaming",
         "originalText":"Aspect          v1                     v2\nEnv required    Yes                    No\nTransport       WebSocket + Hybrid     SSE + CCRClient\nAuth            env_secret -> worker   OAuth JWT\n                jwt                    \nComplexity      4 API calls            2 API calls\nRoundtrips      3 before streaming     1 before streaming",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#A0AEC0","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":30103,"version":1,"versionNonce":30104,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"comp_box","lineHeight":1.25},

        # Insight
        {"type":"rectangle","id":"insight_box","x":40,"y":600,"width":700,"height":55,
         "strokeColor":"#6C63FF","backgroundColor":"#0D1117","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":30201,"version":1,"versionNonce":30202,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"insight_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"insight_text","x":60,"y":605,"width":660,"height":45,
         "text":"Insight: v2 cuts the environment abstraction entirely -- sessions authenticate directly\nwith OAuth, removing a whole layer of state management.",
         "originalText":"Insight: v2 cuts the environment abstraction entirely -- sessions authenticate directly\nwith OAuth, removing a whole layer of state management.",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":30203,"version":1,"versionNonce":30204,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"insight_box","lineHeight":1.25},
    ]

    data = {
        "type": "excalidraw",
        "version": 2,
        "source": "https://excalidraw.com",
        "elements": elements,
        "appState": {"viewBackgroundColor": "#0F0F1A", "gridSize": 20},
        "files": {}
    }

    path = "C:/Users/Administrator/Desktop/deep-dive/ch08-protocol/diagrams/bridge-v1-vs-v2.excalidraw"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    with open(path, "r", encoding="utf-8") as f:
        json.loads(f.read())
    print("Diagram 1: Valid JSON, written successfully")


def write_d2():
    """v2 SSE lifecycle - horizontal timeline"""
    em_dash = "\u2014"
    elements = [
        # Title
        {"type":"text","id":"title","x":100,"y":10,"width":600,"height":28,
         "text":"v2 Bridge SSE Connection Lifecycle",
         "originalText":"v2 Bridge SSE Connection Lifecycle",
         "fontSize":20,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40001,"version":1,"versionNonce":40002,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Timeline spine (horizontal line)
        {"type":"line","id":"spine","x":80,"y":120,
         "strokeColor":"#2D3748","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40100,"version":1,"versionNonce":40101,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,
         "points":[[0,0],[740,0]]},

        # Phase 1: Auth
        {"type":"ellipse","id":"p1_dot","x":100,"y":112,"width":16,"height":16,
         "strokeColor":"#00D4AA","backgroundColor":"#00D4AA","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40101,"version":1,"versionNonce":40102,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False},
        {"type":"text","id":"p1_label","x":60,"y":75,"width":100,"height":18,
         "text":"Auth (OAuth)",
         "originalText":"Auth (OAuth)",
         "fontSize":14,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40103,"version":1,"versionNonce":40104,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},
        {"type":"rectangle","id":"p1_box","x":40,"y":140,"width":140,"height":60,
         "strokeColor":"#00D4AA","backgroundColor":"#16213E","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40105,"version":1,"versionNonce":40106,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"p1_detail","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"p1_detail","x":50,"y":145,"width":120,"height":50,
         "text":"POST /v1/code/sessions\nOAuth token -> session_id",
         "originalText":"POST /v1/code/sessions\nOAuth token -> session_id",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40107,"version":1,"versionNonce":40108,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"p1_box","lineHeight":1.25},
        {"type":"text","id":"p1_note","x":40,"y":210,"width":140,"height":25,
         "text":"No env_id, no env_secret -- pure OAuth",
         "originalText":"No env_id, no env_secret -- pure OAuth",
         "fontSize":9,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#718096","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40109,"version":1,"versionNonce":40110,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Phase 2: Bridge Setup
        {"type":"ellipse","id":"p2_dot","x":270,"y":112,"width":16,"height":16,
         "strokeColor":"#6C63FF","backgroundColor":"#6C63FF","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40201,"version":1,"versionNonce":40202,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False},
        {"type":"text","id":"p2_label","x":230,"y":75,"width":110,"height":18,
         "text":"Bridge Setup",
         "originalText":"Bridge Setup",
         "fontSize":14,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40203,"version":1,"versionNonce":40204,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},
        {"type":"rectangle","id":"p2_box","x":210,"y":140,"width":140,"height":60,
         "strokeColor":"#6C63FF","backgroundColor":"#1A1A2E","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40205,"version":1,"versionNonce":40206,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"p2_detail","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"p2_detail","x":220,"y":145,"width":120,"height":50,
         "text":"POST /sessions/{id}/bridge\nworker_jwt + expires_in + api_base + epoch",
         "originalText":"POST /sessions/{id}/bridge\nworker_jwt + expires_in + api_base + epoch",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40207,"version":1,"versionNonce":40208,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"p2_box","lineHeight":1.25},
        {"type":"text","id":"p2_note","x":210,"y":210,"width":150,"height":25,
         "text":"Worker epoch enables server-side timeout tracking",
         "originalText":"Worker epoch enables server-side timeout tracking",
         "fontSize":9,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#718096","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40209,"version":1,"versionNonce":40210,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Phase 3: SSE Connect
        {"type":"ellipse","id":"p3_dot","x":440,"y":112,"width":16,"height":16,
         "strokeColor":"#00D4AA","backgroundColor":"#00D4AA","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40301,"version":1,"versionNonce":40302,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False},
        {"type":"text","id":"p3_label","x":400,"y":75,"width":110,"height":18,
         "text":"SSE Connect",
         "originalText":"SSE Connect",
         "fontSize":14,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40303,"version":1,"versionNonce":40304,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},
        {"type":"rectangle","id":"p3_box","x":380,"y":140,"width":140,"height":60,
         "strokeColor":"#00D4AA","backgroundColor":"#152A20","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40305,"version":1,"versionNonce":40306,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"p3_detail","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"p3_detail","x":390,"y":145,"width":120,"height":50,
         "text":"Open SSE stream to api_base/sse\nBidirectional channel established",
         "originalText":"Open SSE stream to api_base/sse\nBidirectional channel established",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40307,"version":1,"versionNonce":40308,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"p3_box","lineHeight":1.25},
        {"type":"text","id":"p3_note","x":380,"y":210,"width":140,"height":25,
         "text":"Server-Sent Events for low-friction streaming",
         "originalText":"Server-Sent Events for low-friction streaming",
         "fontSize":9,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#718096","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40309,"version":1,"versionNonce":40310,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Phase 4: Active
        {"type":"ellipse","id":"p4_dot","x":610,"y":112,"width":16,"height":16,
         "strokeColor":"#00D4AA","backgroundColor":"#00D4AA","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40401,"version":1,"versionNonce":40402,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False},
        {"type":"text","id":"p4_label","x":570,"y":75,"width":90,"height":18,
         "text":"Active",
         "originalText":"Active",
         "fontSize":14,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40403,"version":1,"versionNonce":40404,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},
        {"type":"rectangle","id":"p4_box","x":540,"y":140,"width":160,"height":60,
         "strokeColor":"#00D4AA","backgroundColor":"#16213E","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40405,"version":1,"versionNonce":40406,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"p4_detail","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"p4_detail","x":550,"y":145,"width":140,"height":50,
         "text":"Session runs, streams results\nvia SSE events (command, result)",
         "originalText":"Session runs, streams results\nvia SSE events (command, result)",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40407,"version":1,"versionNonce":40408,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"p4_box","lineHeight":1.25},

        # Phase 5: JWT Refresh (loop back arrow)
        {"type":"arrow","id":"refresh_arrow","x":350,"y":85,"width":0,"height":0,
         "strokeColor":"#FFB84D","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40501,"version":1,"versionNonce":40502,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,
         "points":[[0,0],[-70,0],[-70,-20],[-140,-20]],
         "startArrowhead":"arrow","endArrowhead":"arrow"},
        {"type":"text","id":"refresh_label","x":210,"y":52,"width":180,"height":18,
         "text":"JWT Refresh (proactive, before expiry)",
         "originalText":"JWT Refresh (proactive, before expiry)",
         "fontSize":11,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#FFB84D","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40503,"version":1,"versionNonce":40504,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Phase 6: Heartbeat (loop below)
        {"type":"arrow","id":"heartbeat_arrow","x":530,"y":240,"width":0,"height":0,
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"dashed","roughness":0,"opacity":100,"angle":0,
         "seed":40601,"version":1,"versionNonce":40602,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,
         "points":[[0,0],[-80,0],[-80,30],[80,30]],
         "startArrowhead":None,"endArrowhead":"arrow"},
        {"type":"text","id":"heartbeat_label","x":390,"y":275,"width":200,"height":20,
         "text":"Heartbeat: periodic ping (20s) + jitter (10%)",
         "originalText":"Heartbeat: periodic ping (20s) + jitter (10%)",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40603,"version":1,"versionNonce":40604,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Phase 7: Disconnect/Reconnect
        {"type":"ellipse","id":"p7_dot","x":700,"y":112,"width":16,"height":16,
         "strokeColor":"#FF6B6B","backgroundColor":"#FF6B6B","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40701,"version":1,"versionNonce":40702,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False},
        {"type":"text","id":"p7_label","x":650,"y":75,"width":130,"height":18,
         "text":"Disconnect/Reconnect",
         "originalText":"Disconnect/Reconnect",
         "fontSize":14,"fontFamily":3,"textAlign":"center","verticalAlign":"top",
         "strokeColor":"#FF6B6B","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40703,"version":1,"versionNonce":40704,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},
        {"type":"rectangle","id":"p7_box","x":620,"y":140,"width":160,"height":60,
         "strokeColor":"#FF6B6B","backgroundColor":"#2A1520","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40705,"version":1,"versionNonce":40706,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"p7_detail","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"p7_detail","x":630,"y":145,"width":140,"height":50,
         "text":"Backoff: 1s->2s->4s->8s\nReconnect with new JWT + seq",
         "originalText":"Backoff: 1s->2s->4s->8s\nReconnect with new JWT + seq",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40707,"version":1,"versionNonce":40708,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"p7_box","lineHeight":1.25},
        {"type":"text","id":"p7_note","x":620,"y":210,"width":170,"height":25,
         "text":"Reconnect with backoff + new JWT if needed",
         "originalText":"Reconnect with backoff + new JWT if needed",
         "fontSize":9,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#718096","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40709,"version":1,"versionNonce":40710,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Insight box
        {"type":"rectangle","id":"insight_box","x":40,"y":310,"width":740,"height":65,
         "strokeColor":"#6C63FF","backgroundColor":"#0D1117","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40801,"version":1,"versionNonce":40802,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"insight_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"insight_text","x":60,"y":315,"width":700,"height":55,
         "text":"The lifecycle is designed for the cloud -- a CLI process on localhost connects to a\ncloud bridge that manages the actual agent. Connection resilience (reconnect with backoff)\nis built into the transport layer.",
         "originalText":"The lifecycle is designed for the cloud -- a CLI process on localhost connects to a\ncloud bridge that manages the actual agent. Connection resilience (reconnect with backoff)\nis built into the transport layer.",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40803,"version":1,"versionNonce":40804,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"insight_box","lineHeight":1.25},

        # Code evidence artifact
        {"type":"rectangle","id":"code_box","x":40,"y":395,"width":740,"height":50,
         "strokeColor":"#2D3748","backgroundColor":"#0D1117","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40901,"version":1,"versionNonce":40902,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"code_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"code_text","x":60,"y":400,"width":700,"height":40,
         "text":"// bridge response -> {worker_jwt, expires_in, api_base_url, worker_epoch}\n// epoch bumps on every /bridge call; old worker gets 409 on heartbeat",
         "originalText":"// bridge response -> {worker_jwt, expires_in, api_base_url, worker_epoch}\n// epoch bumps on every /bridge call; old worker gets 409 on heartbeat",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#79C0FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":40903,"version":1,"versionNonce":40904,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"code_box","lineHeight":1.25},
    ]

    data = {
        "type": "excalidraw",
        "version": 2,
        "source": "https://excalidraw.com",
        "elements": elements,
        "appState": {"viewBackgroundColor": "#0F0F1A", "gridSize": 20},
        "files": {}
    }

    path = "C:/Users/Administrator/Desktop/deep-dive/ch08-protocol/diagrams/v2-sse-lifecycle.excalidraw"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    with open(path, "r", encoding="utf-8") as f:
        json.loads(f.read())
    print("Diagram 2: Valid JSON, written successfully")


def write_d3():
    """Bridge resilience - three concentric rings / nested boxes"""
    elements = [
        # Title
        {"type":"text","id":"title","x":40,"y":10,"width":600,"height":28,
         "text":"Bridge Resilience - Dedup + Backoff + Circuit Breaker",
         "originalText":"Bridge Resilience - Dedup + Backoff + Circuit Breaker",
         "fontSize":20,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50001,"version":1,"versionNonce":50002,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Flow arrow at top
        {"type":"text","id":"flow_label","x":40,"y":50,"width":300,"height":16,
         "text":"Error -> Ring 1 (Dedup) -> Ring 2 (Backoff) -> Ring 3 (Circuit Breaker)",
         "originalText":"Error -> Ring 1 (Dedup) -> Ring 2 (Backoff) -> Ring 3 (Circuit Breaker)",
         "fontSize":11,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#A0AEC0","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50003,"version":1,"versionNonce":50004,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Outer box: Circuit Breaker
        {"type":"rectangle","id":"ring3","x":40,"y":80,"width":740,"height":370,
         "strokeColor":"#FF6B6B","backgroundColor":"#2A1520","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50101,"version":1,"versionNonce":50102,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"ring3_label","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"ring3_label","x":55,"y":90,"width":300,"height":22,
         "text":"Ring 3 -- Circuit Breaker",
         "originalText":"Ring 3 -- Circuit Breaker",
         "fontSize":14,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#FF6B6B","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50103,"version":1,"versionNonce":50104,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"ring3","lineHeight":1.25},

        # Circuit breaker bullets
        {"type":"text","id":"r3_b1","x":70,"y":120,"width":350,"height":16,
         "text":"N consecutive failures -> circuit opens",
         "originalText":"N consecutive failures -> circuit opens",
         "fontSize":11,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50105,"version":1,"versionNonce":50106,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},
        {"type":"text","id":"r3_b2","x":70,"y":145,"width":350,"height":16,
         "text":"Stops all retry attempts, reports unreachable",
         "originalText":"Stops all retry attempts, reports unreachable",
         "fontSize":11,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50107,"version":1,"versionNonce":50108,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},
        {"type":"text","id":"r3_b3","x":70,"y":170,"width":350,"height":16,
         "text":"Cooldown -> half-open -> single test attempt",
         "originalText":"Cooldown -> half-open -> single test attempt",
         "fontSize":11,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50109,"version":1,"versionNonce":50110,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},
        {"type":"text","id":"r3_note","x":70,"y":200,"width":350,"height":25,
         "text":"Last line of defense: prevents infinite retry loops",
         "originalText":"Last line of defense: prevents infinite retry loops",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#A0AEC0","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50111,"version":1,"versionNonce":50112,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Middle box: Backoff Matrix
        {"type":"rectangle","id":"ring2","x":60,"y":240,"width":700,"height":200,
         "strokeColor":"#FFB84D","backgroundColor":"#1E2D4A","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50201,"version":1,"versionNonce":50202,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"ring2_label","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"ring2_label","x":75,"y":250,"width":300,"height":22,
         "text":"Ring 2 -- Backoff Matrix",
         "originalText":"Ring 2 -- Backoff Matrix",
         "fontSize":14,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#FFB84D","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50203,"version":1,"versionNonce":50204,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"ring2","lineHeight":1.25},

        # Backoff details - Network
        {"type":"rectangle","id":"b_network","x":75,"y":285,"width":190,"height":70,
         "strokeColor":"#00D4AA","backgroundColor":"#16213E","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50205,"version":1,"versionNonce":50206,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"b_network_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"b_network_text","x":85,"y":290,"width":170,"height":60,
         "text":"Network failure\n1s -> 2s -> 4s -> 8s\n(fast recovery)",
         "originalText":"Network failure\n1s -> 2s -> 4s -> 8s\n(fast recovery)",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50207,"version":1,"versionNonce":50208,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"b_network","lineHeight":1.25},

        # Backoff details - Server error
        {"type":"rectangle","id":"b_server","x":285,"y":285,"width":190,"height":70,
         "strokeColor":"#FFB84D","backgroundColor":"#0D1117","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50209,"version":1,"versionNonce":50210,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"b_server_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"b_server_text","x":295,"y":290,"width":170,"height":60,
         "text":"Server error\n5s -> 10s -> 20s\n(server is struggling)",
         "originalText":"Server error\n5s -> 10s -> 20s\n(server is struggling)",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50211,"version":1,"versionNonce":50212,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"b_server","lineHeight":1.25},

        # Backoff details - Auth failure
        {"type":"rectangle","id":"b_auth","x":495,"y":285,"width":190,"height":70,
         "strokeColor":"#FF6B6B","backgroundColor":"#2A1520","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50213,"version":1,"versionNonce":50214,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"b_auth_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"b_auth_text","x":505,"y":290,"width":170,"height":60,
         "text":"Auth failure\nNo backoff, fail immediately\n(wont help to retry)",
         "originalText":"Auth failure\nNo backoff, fail immediately\n(wont help to retry)",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#FFFFFF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50215,"version":1,"versionNonce":50216,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"b_auth","lineHeight":1.25},

        {"type":"text","id":"ring2_note","x":75,"y":375,"width":650,"height":20,
         "text":"Per-connection backoff, not global -- multiple bridges retry independently",
         "originalText":"Per-connection backoff, not global -- multiple bridges retry independently",
         "fontSize":10,"fontFamily":3,"textAlign":"left","verticalAlign":"top",
         "strokeColor":"#A0AEC0","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50217,"version":1,"versionNonce":50218,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":None,"lineHeight":1.25},

        # Inner box: Deduplication
        {"type":"rectangle","id":"ring1","x":80,"y":395,"width":660,"height":45,
         "strokeColor":"#00D4AA","backgroundColor":"#152A20","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50301,"version":1,"versionNonce":50302,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"ring1_label","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"ring1_label","x":90,"y":400,"width":640,"height":35,
         "text":"Ring 1 -- Deduplication (BoundedUUIDSet): Tracks recently seen UUIDs in ring buffer (cap: 2000). SSE duplicate on reconnect is skipped. Oldest entries evicted first.",
         "originalText":"Ring 1 -- Deduplication (BoundedUUIDSet): Tracks recently seen UUIDs in ring buffer (cap: 2000). SSE duplicate on reconnect is skipped. Oldest entries evicted first.",
         "fontSize":11,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#00D4AA","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50303,"version":1,"versionNonce":50304,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"ring1","lineHeight":1.25},

        # Insight box
        {"type":"rectangle","id":"insight_box","x":40,"y":455,"width":740,"height":45,
         "strokeColor":"#6C63FF","backgroundColor":"#0D1117","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50401,"version":1,"versionNonce":50402,"isDeleted":False,"groupIds":[],
         "boundElements":[{"id":"insight_text","type":"text"}],"link":None,
         "locked":False,"roundness":{"type":3}},
        {"type":"text","id":"insight_text","x":60,"y":460,"width":700,"height":35,
         "text":"Three layers of resilience work together: dedup prevents re-processing, backoff adapts to fault type, circuit breaker stops infinite retries.",
         "originalText":"Three layers of resilience work together: dedup prevents re-processing, backoff adapts to fault type, circuit breaker stops infinite retries.",
         "fontSize":12,"fontFamily":3,"textAlign":"left","verticalAlign":"middle",
         "strokeColor":"#6C63FF","backgroundColor":"transparent","fillStyle":"solid",
         "strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,
         "seed":50403,"version":1,"versionNonce":50404,"isDeleted":False,"groupIds":[],
         "boundElements":None,"link":None,"locked":False,"containerId":"insight_box","lineHeight":1.25},
    ]

    data = {
        "type": "excalidraw",
        "version": 2,
        "source": "https://excalidraw.com",
        "elements": elements,
        "appState": {"viewBackgroundColor": "#0F0F1A", "gridSize": 20},
        "files": {}
    }

    path = "C:/Users/Administrator/Desktop/deep-dive/ch08-protocol/diagrams/bridge-resilience-ring.excalidraw"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    with open(path, "r", encoding="utf-8") as f:
        json.loads(f.read())
    print("Diagram 3: Valid JSON, written successfully")


if __name__ == "__main__":
    write_d1()
    write_d2()
    write_d3()
